server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Gussoft/micro-conf
          search-paths: config-data
  application:
    name: config-service